# Generated by Django 4.1.1 on 2022-09-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biciapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='password',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
